name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:


permissions:
  security-events: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vuln-app ./app

      - name: Save Docker Image as tar
        run: docker save vuln-app -o vuln-app.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vuln-app-image
          path: vuln-app.tar

  Container-Image-Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: vuln-app-image

      - name: Load image into Docker
        run: docker load -i vuln-app.tar

      - name: Trivy - Container OS scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: vuln-app
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os'
          format: sarif
          output: trivy-image.sarif

      - name: Upload container scan results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-image.sarif
          category: container-scan

  Dependency-Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy - Dependency scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: ./app/requirements.txt
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          format: sarif
          output: trivy-deps.sarif

      - name: Upload dependency scan results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-deps.sarif
          category: dependency-scan

          